### ISSUE TITLE
error while performing Asset Creation

### ISSUE THREAD

**Issue by amarun22** [artusvranken/FarmToFork#1]
Getting the below error, when tried creating asset: 
Object { message: "HTTP Error: Requested page not reac…", status: "400 BAD REQUEST", requestURI: "https://test.bigchaindb.com/api/v1/…" }  bundle.js:6233:489238

**Comment by artus** [comment]
The application runs on the BigchainDB test-network, which was being stress-tested at the time (and maybe still is at the moment). Another reason could be that the [js-bigchaindb-driver](https://github.com/bigchaindb/js-bigchaindb-driver) was not updated to the latest version. Whatever the case, it is fixed now.
